//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Argix.Finance {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Summary : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumBillToAddress;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumBillToName;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumBillToCityStateZip;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumInvoice;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumManifests;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumInvoiceDate;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumReleaseDate;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumCartons;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumWeight;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumTotalCharge;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumRemitToName;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumRemitToAddress;
        
        internal Microsoft.Office.Tools.Excel.NamedRange SumRemitToCityStateZip;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Summary(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet1", "Sheet1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Summary = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.SumBillToAddress.BeginInit();
            this.SumBillToName.BeginInit();
            this.SumBillToCityStateZip.BeginInit();
            this.SumInvoice.BeginInit();
            this.SumManifests.BeginInit();
            this.SumInvoiceDate.BeginInit();
            this.SumReleaseDate.BeginInit();
            this.SumCartons.BeginInit();
            this.SumWeight.BeginInit();
            this.SumTotalCharge.BeginInit();
            this.SumRemitToName.BeginInit();
            this.SumRemitToAddress.BeginInit();
            this.SumRemitToCityStateZip.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.SumRemitToCityStateZip.EndInit();
            this.SumRemitToAddress.EndInit();
            this.SumRemitToName.EndInit();
            this.SumTotalCharge.EndInit();
            this.SumWeight.EndInit();
            this.SumCartons.EndInit();
            this.SumReleaseDate.EndInit();
            this.SumInvoiceDate.EndInit();
            this.SumManifests.EndInit();
            this.SumInvoice.EndInit();
            this.SumBillToCityStateZip.EndInit();
            this.SumBillToName.EndInit();
            this.SumBillToAddress.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.SumBillToAddress = Globals.Factory.CreateNamedRange(null, null, "SumBillToAddress", "SumBillToAddress", this);
            this.SumBillToName = Globals.Factory.CreateNamedRange(null, null, "SumBillToName", "SumBillToName", this);
            this.SumBillToCityStateZip = Globals.Factory.CreateNamedRange(null, null, "SumBillToCityStateZip", "SumBillToCityStateZip", this);
            this.SumInvoice = Globals.Factory.CreateNamedRange(null, null, "SumInvoice", "SumInvoice", this);
            this.SumManifests = Globals.Factory.CreateNamedRange(null, null, "SumManifests", "SumManifests", this);
            this.SumInvoiceDate = Globals.Factory.CreateNamedRange(null, null, "SumInvoiceDate", "SumInvoiceDate", this);
            this.SumReleaseDate = Globals.Factory.CreateNamedRange(null, null, "SumReleaseDate", "SumReleaseDate", this);
            this.SumCartons = Globals.Factory.CreateNamedRange(null, null, "SumCartons", "SumCartons", this);
            this.SumWeight = Globals.Factory.CreateNamedRange(null, null, "SumWeight", "SumWeight", this);
            this.SumTotalCharge = Globals.Factory.CreateNamedRange(null, null, "SumTotalCharge", "SumTotalCharge", this);
            this.SumRemitToName = Globals.Factory.CreateNamedRange(null, null, "SumRemitToName", "SumRemitToName", this);
            this.SumRemitToAddress = Globals.Factory.CreateNamedRange(null, null, "SumRemitToAddress", "SumRemitToAddress", this);
            this.SumRemitToCityStateZip = Globals.Factory.CreateNamedRange(null, null, "SumRemitToCityStateZip", "SumRemitToCityStateZip", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // SumBillToAddress
            // 
            this.SumBillToAddress.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumBillToName
            // 
            this.SumBillToName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumBillToCityStateZip
            // 
            this.SumBillToCityStateZip.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumInvoice
            // 
            this.SumInvoice.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumManifests
            // 
            this.SumManifests.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumInvoiceDate
            // 
            this.SumInvoiceDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumReleaseDate
            // 
            this.SumReleaseDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumCartons
            // 
            this.SumCartons.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumWeight
            // 
            this.SumWeight.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumTotalCharge
            // 
            this.SumTotalCharge.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumRemitToName
            // 
            this.SumRemitToName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumRemitToAddress
            // 
            this.SumRemitToAddress.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // SumRemitToCityStateZip
            // 
            this.SumRemitToCityStateZip.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Summary
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.SumRemitToCityStateZip.Dispose();
            this.SumRemitToAddress.Dispose();
            this.SumRemitToName.Dispose();
            this.SumTotalCharge.Dispose();
            this.SumWeight.Dispose();
            this.SumCartons.Dispose();
            this.SumReleaseDate.Dispose();
            this.SumInvoiceDate.Dispose();
            this.SumManifests.Dispose();
            this.SumInvoice.Dispose();
            this.SumBillToCityStateZip.Dispose();
            this.SumBillToName.Dispose();
            this.SumBillToAddress.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Summary _Summary;
        
        internal static Summary Summary {
            get {
                return _Summary;
            }
            set {
                if ((_Summary == null)) {
                    _Summary = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
